version: '3.8'

services:
  # Serviço do Banco de Dados (PostgreSQL)
  db:
    image: postgres:15-alpine
    container_name: next_event_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Serviço do Back-end (Node.js + Express + Prisma)
  backend:
    container_name: next_event_backend
    build:
      context: ./BackEnd
      dockerfile: Dockerfile
    # Mapeia a porta 4000 do seu PC para a 3000 do Container
    ports:
      - "4000:3000"
    environment:
      - NODE_ENV=production
      # Conexão interna com o container 'db'
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}?schema=public
      - JWT_SECRET=${JWT_SECRET}
      - PORT=3000
    depends_on:
      db:
        condition: service_healthy
    # Aguarda o banco estar pronto, roda as migrações e inicia o servidor
    command: sh -c "npx prisma migrate deploy && npm start"

  # Serviço do Front-end (React + Nginx)
  frontend:
    container_name: next_event_frontend
    build:
      context: ./FrontEnd
      dockerfile: Dockerfile
    # Mapeia a porta 3000 do seu PC para a 80 do Nginx
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres-data: